website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, session
from flask_login import login_user, login_required, logout_user, current_user
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db

auth = Blueprint('auth', __name__)



@auth.route('/login', methods=['GET', 'POST'])
def login():
    # code here
    if (current_user.is_authenticated):
        flash('Cannot Access Login, You Are Already Logged In.', category='error')
        return redirect(url_for('views.home'))
    
    if (request.method == 'POST'):
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()

        if(user):
            if(check_password_hash(user.password, password)):
                flash('Login Successful.', category='success')
                login_user(user, remember=True) # logs the user in, passes in to pages with flask module thingy
                return redirect(url_for('views.home'))
                
            else: # password incorrect
                flash('Failed to login, please check your username and/or password.', category='error')

        else: # user does not exist, the flash is left the same intentionally
            flash('Failed to login, please try again.', category='error')
            
    return render_template("LoginPage.html")



@auth.route('/logout')
# @login_required # login functionality requirement
def logout():
    if(current_user.is_authenticated):
        logout_user()
        flash('You have successfully logged out.', category='success')
        return redirect(url_for('views.home'))
    else:
        flash('You are not currently logged in.', category='error')
        return redirect(url_for('views.home'))




@auth.route('/signup', methods=['GET', 'POST'])
def sign_up():
    if (current_user.is_authenticated):
        flash('Cannot Access Account Sign Up While Logged In.', category='error')
        return redirect(url_for('views.home'))

    data = request.form
    if (request.method == 'POST'):
        email = request.form.get('email')
        firstname = request.form.get('firstname')
        lastname = request.form.get('lastname')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')
        securityQuestion = request.form.get('SecurityQuestionInput')
        securityAnswer = request.form.get('SecurityAnswer')

        user_exists = User.query.filter_by(email=email).first()
        if (user_exists):
            #Post error message saying user with that email alreay exists
            flash('Email Provided Already Has Account!', category='error')
        else:
            #create user
            new_user = User(email=email, first_name=firstname, last_name=lastname, password=generate_password_hash(password1), security_prompt=securityQuestion, security_answer=securityAnswer)
            db.session.add(new_user)
            db.session.commit()
            flash('Account Created!', category='success')

            login_user(new_user, remember=True) # create and pass in user object 

            return redirect(url_for('views.home'))

    return render_template("Signup.html", user=current_user)



@auth.route('/forgotPassword1', methods=['GET', 'POST'])
def forgotPassword1():
    if (request.method == 'POST'):
        email = request.form.get('email')

        user_exists = User.query.filter_by(email=email).first()
        if (user_exists):
            return redirect(url_for('auth.forgotPassword2', email=email))
        else:
            flash("Email Provided Doesn't Have An Account!", category='error')
    
    return render_template("forgotPassword1.html")



@auth.route('/forgotPassword2', methods=['GET', 'POST'])
def forgotPassword2():
    if (request.method == 'GET'):
        email = request.args.get('email')
        if (not email):
            return redirect(url_for('views.home'))
        else:
            user = User.query.filter_by(email=email).first()
            secPrompt = user.security_prompt
            
            if (secPrompt == 1):
                secPrompt = "Name of the street you grew up on"
            elif (secPrompt == 2):
                secPrompt = "Mother's maiden name"
            elif (secPrompt == 3):
                secPrompt = "Name of your favorite childhood pet"
            elif (secPrompt == 4):
                secPrompt = "Title of your favorite movie"
            
            return render_template("forgotPassword2.html", email=email, secPrompt=secPrompt)

    if (request.method == 'POST'):
        email = request.form.get('email')
        secPrompt = request.form.get('SecurityQuestionInput')
        user = User.query.filter_by(email=email).first()
        secAnswer = request.form.get('SecurityAnswer')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        if (secAnswer == user.security_answer):
            #Change Password to New Password and Make suree to has the password
            user.password = generate_password_hash(password1)
            db.session.commit()
            flash('Password Change Successful. Proceed to Login.', category='success')
            return redirect(url_for('views.home'))
        else:
            flash('The Answer The Security Question Is Incorrect. Password Change Failed!', category='error')
            return render_template("forgotPassword2.html", email=email, secPrompt=secPrompt)
    
    return redirect(url_for('views.home'))

website/views.py
from flask import Blueprint, render_template, url_for, redirect, flash, request
from flask_login import login_user, login_required, logout_user, current_user
from .models import User, General_Recipe, Cookbook, Cookbook_Recipe
from . import db


views = Blueprint('views', __name__)

@views.route('/')
def home():
    return render_template("Home.html", user=current_user)

@views.route('/MyCookbooks', methods=['GET', 'POST'])
# login functionality requirement
def Cookbooks():
    if(current_user.is_authenticated):
        if (request.method == 'POST'):
            if (request.form.get('HiddenCreateCookbookFormIdentifier') == "CreateCookbookForm"):
                title = request.form.get('cookbook_title')
                description = request.form.get('cookbook_desc')
                
                new_cookbook = Cookbook(user_id=current_user.id, title=title, description=description, recipe_count=0)
                db.session.add(new_cookbook)
                db.session.commit()
                flash('Cookbook Created!', category='success')

            return render_template("MyCookbooks.html", user=current_user)
        else:    
            return render_template("MyCookbooks.html", user=current_user)
    else:
        flash('You need to log in to view this page', category='error')
        return redirect(url_for('views.home'))

@views.route('/CookbookView', methods=['GET', 'POST'])
def CookbookView():
    cookbook_id = request.args.get('cookbook_id')
    if (not cookbook_id or request.method != 'GET'):
        if (cookbook_id and request.method == 'POST'):
            if (request.form.get('HiddenRecipeDeleteForm') != None):
                recipe_id = request.form.get('HiddenRecipeDeleteForm')
                recipe_exists = Cookbook_Recipe.query.filter_by(id=recipe_id, user_id=current_user.id, cookbook_id=cookbook_id).first()
                the_cookbook = Cookbook.query.filter_by(user_id=current_user.id, id=cookbook_id).first()
                if (recipe_exists):
                    db.session.delete(recipe_exists)
                    the_cookbook.recipe_count -= 1
                    db.session.commit()
                    flash('Recipe Successfully Deleted!', category='success')

                cookbook_recipes = Cookbook_Recipe.query.filter_by(user_id=current_user.id, cookbook_id=cookbook_id).all()
                return render_template("CookbookView.html", user=current_user, the_cookbook=the_cookbook, recipes=cookbook_recipes)
            
            elif (request.form.get('HiddenCbDeleteForm') != None):
                cookbook_id = request.form.get('HiddenCbDeleteForm')
                cookbook_exists = Cookbook.query.filter_by(user_id=current_user.id, id=cookbook_id).first()
                if (cookbook_exists):
                    associated_cookbook_recipes = Cookbook_Recipe.query.filter_by(user_id=current_user.id, cookbook_id=cookbook_id).all()
                    if (associated_cookbook_recipes):
                        for cb_recipe in associated_cookbook_recipes:
                            db.session.delete(cb_recipe)
                        db.session.commit()
                    db.session.delete(cookbook_exists)
                    db.session.commit()
                    flash('Cookbook Successfully Deleted!', category='success')
                return redirect(url_for('views.Cookbooks', user=current_user))
            
            elif (request.form.get('HiddenEditCbForm') != None):
                cookbook_id = request.form.get('HiddenEditCbForm')
                cookbook_exists = Cookbook.query.filter_by(user_id=current_user.id, id=cookbook_id).first()
                if (cookbook_exists):
                    title = request.form.get('edit_cookbook_title')
                    description = request.form.get('edit_cookbook_desc')
                    cookbook_exists.title = title
                    cookbook_exists.description = description
                    db.session.commit()
                    flash('Cookbook Successfully Changed!', category='success')
                cookbook_recipes = Cookbook_Recipe.query.filter_by(user_id=current_user.id, cookbook_id=cookbook_id).all()
                return render_template("CookbookView.html", user=current_user, the_cookbook=cookbook_exists, recipes=cookbook_recipes)

                
        return redirect(url_for('views.home'))
    else:
        the_cookbook = Cookbook.query.filter_by(user_id=current_user.id, id=cookbook_id).first()
        cookbook_recipes = Cookbook_Recipe.query.filter_by(user_id=current_user.id, cookbook_id=cookbook_id).all()
        return render_template("CookbookView.html", user=current_user, the_cookbook=the_cookbook, recipes=cookbook_recipes)

@views.route('/CookbookRecipeView', methods=['GET', 'POST'])
def CookbookRecipeView():
    recipe_id = request.args.get('recipe_id')
    cookbook_id = request.args.get('cookbook_id')
    if (not recipe_id or not cookbook_id or request.method != 'GET'):
        notes_data = request.form.get('notesText')
        if (recipe_id and cookbook_id and notes_data != None):
            recipe = Cookbook_Recipe.query.filter_by(user_id=current_user.id, cookbook_id=cookbook_id, id=recipe_id).first()
            ingredient_list = recipe.ingredients.split('\n')
            opt_ingredient_list = []
            opt_ingredient_list = recipe.optional_ingredients.split('\n')
            instruction_list = recipe.instructions.split('\n')
            
            recipe.notes = notes_data
            db.session.commit()
            flash('Recipe Notes Updated Successfully', category='success')

            return render_template("CookbookRecipeView.html", recipe=recipe, ingredient_list=ingredient_list, opt_ingredient_list=opt_ingredient_list, instruction_list=instruction_list)

        return redirect(url_for('views.home'))
    else:
        recipe = Cookbook_Recipe.query.filter_by(user_id=current_user.id, cookbook_id=cookbook_id, id=recipe_id).first()
        ingredient_list = recipe.ingredients.split('\n')
        opt_ingredient_list = []
        opt_ingredient_list = recipe.optional_ingredients.split('\n')
        instruction_list = recipe.instructions.split('\n')
        return render_template("CookbookRecipeView.html", recipe=recipe, ingredient_list=ingredient_list, opt_ingredient_list=opt_ingredient_list, instruction_list=instruction_list)

@views.route('/Explore', methods=['GET', 'POST'])
def Explore():
    if (request.method == 'POST'):
        search_term = request.form.get('searchbox', '').strip()

        # Get filter values from the form
        breakfast = request.form.get('is_breakfast')
        lunch = request.form.get('is_lunch')
        dinner = request.form.get('is_dinner')
        snack = request.form.get('is_snack')
        appetizer = request.form.get('is_appetizer')
        entree = request.form.get('is_entree')
        dessert = request.form.get('is_dessert')
        sidedish = request.form.get('is_sidedish')
        italian = request.form.get('is_italian')
        chinese = request.form.get('is_chinese')
        mexican = request.form.get('is_mexican')
        indian = request.form.get('is_indian')
        american = request.form.get('is_american')
        mediterranean = request.form.get('is_mediterranean')

        query_string_list = ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '']
        query = General_Recipe.query

        # Apply search term filter if present
        if search_term:
            query = query.filter(General_Recipe.title.ilike(f"%{search_term}%"))
            query_string_list[0] = search_term

        # Filter by meal type
        if breakfast:
            query = query.filter(General_Recipe.is_breakfast == True)
            query_string_list[1] = 'checked'
        if lunch:
            query = query.filter(General_Recipe.is_lunch == True)
            query_string_list[2] = 'checked'
        if dinner:
            query = query.filter(General_Recipe.is_dinner == True)
            query_string_list[3] = 'checked'
        if snack:
            query = query.filter(General_Recipe.is_snack == True)
            query_string_list[4] = 'checked'
        if appetizer:
            query = query.filter(General_Recipe.is_appetizer == True)
            query_string_list[5] = 'checked'
        if entree:
            query = query.filter(General_Recipe.is_entree == True)
            query_string_list[6] = 'checked'
        if dessert:
            query = query.filter(General_Recipe.is_dessert == True)
            query_string_list[7] = 'checked'
        if sidedish:
            query = query.filter(General_Recipe.is_sidedish == True)
            query_string_list[8] = 'checked'

        # Cuisine filters
        cuisine_filters = []
        if american:
            cuisine_filters.append(General_Recipe.is_american)
            query_string_list[9] = 'checked'
        if chinese:
            cuisine_filters.append(General_Recipe.is_chinese)
            query_string_list[10] = 'checked'
        if indian:
            cuisine_filters.append(General_Recipe.is_indian)
            query_string_list[11] = 'checked'
        if italian:
            cuisine_filters.append(General_Recipe.is_italian)
            query_string_list[12] = 'checked'
        if mediterranean:
            cuisine_filters.append(General_Recipe.is_mediterranean)
            query_string_list[13] = 'checked'
        if mexican:
            cuisine_filters.append(General_Recipe.is_mexican)
            query_string_list[14] = 'checked'

        # Query for recipes matching all selected cuisines
        primary_query = query
        for filter_condition in cuisine_filters:
            primary_query = primary_query.filter(filter_condition == True)
        primary_recipes = primary_query.all()


website/templates/Explore.html
{% extends "base.html" %} 
{% block title %}Explore{% endblock %}

{% block content %}
<h1 align="center">Explore</h1>
<hr style="color: white; margin: 0px;">
<div class="container-fluid">
  <div class="row">
    <!-- Left Column (Filter and Search) -->
    <div class="col-lg-2 col-md-2" style="margin-left: 25px; margin-right: 25px; margin-top: 10px;">
      <form class="sticky-top" method="POST" action="{{ url_for('views.Explore') }}" style="top: 30px;">
        <div class="card mb-2" style="box-shadow: 0 0 8px 0 rgba(100, 100, 100, 0.1);">
          <div class="card-body">
            <!-- Search Bar -->
            <h5 class="card-title">Search</h5>
            <input type="text" class="form-control mb-3" name="searchbox" placeholder="Search Recipes..." value="{{ query_string_list[0] }}">
            
            <!-- Filter by Tag Section -->
            <h5 class="card-title d-inline">Filter by <span class="badge badge-tag rounded-pill">Tag</span></h5>
            <hr style="color: white; margin-top: 0px; margin-bottom: 10px;">
            <div class="accordion">
              <!-- Time of Day Section -->
              <div class="accordion-item" id="tags">
                <h6 class="accordion-header"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">Time of Day</button></h6>
                <div id="collapseOne" class="accordion-collapse collapse" data-bs-parent="#tags">
                  <div class="accordion-body" style="padding: 5px;">
                    <ul class="list-group list-group-flush">
                      <li class="list-group-item"><input type="checkbox" name="is_breakfast" {{ query_string_list[1] }}> Breakfast</li>
                      <li class="list-group-item"><input type="checkbox" name="is_lunch" {{ query_string_list[2] }}> Lunch</li>
                      <li class="list-group-item"><input type="checkbox" name="is_dinner" {{ query_string_list[3] }}> Dinner</li>
                      <li class="list-group-item"><input type="checkbox" name="is_snack" {{ query_string_list[4] }}> Snack</li>
                    </ul>
                  </div>
                </div>
              </div>

              <!-- Type of Food Section -->
              <div class="accordion-item">
                <h6 class="accordion-header"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">Type of Dish</button></h6>
                <div id="collapseTwo" class="accordion-collapse collapse" data-bs-parent="#tags">
                  <div class="accordion-body" style="padding: 5px;">
                    <ul class="list-group list-group-flush">
                      <li class="list-group-item"><input type="checkbox" name="is_appetizer" {{ query_string_list[5] }}> Appetizer</li>
                      <li class="list-group-item"><input type="checkbox" name="is_entree" {{ query_string_list[6] }}> Entree</li>
                      <li class="list-group-item"><input type="checkbox" name="is_dessert" {{ query_string_list[7] }}> Dessert</li>
                      <li class="list-group-item"><input type="checkbox" name="is_sidedish" {{ query_string_list[8] }}> Side</li>
                    </ul>
                  </div>
                </div>
              </div>

              <!-- Type of Cuisine Section -->
              <div class="accordion-item">
                <h6 class="accordion-header"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">Cuisine</button></h6>
                <div id="collapseThree" class="accordion-collapse collapse" data-bs-parent="#tags">
                  <div class="accordion-body" style="padding: 5px;">
                    <ul class="list-group list-group-flush">
                      <li class="list-group-item"><input type="checkbox" name="is_american" {{ query_string_list[9] }}> American</li>
                      <li class="list-group-item"><input type="checkbox" name="is_chinese" {{ query_string_list[10] }}> Chinese</li>
                      <li class="list-group-item"><input type="checkbox" name="is_indian" {{ query_string_list[11] }}> Indian</li>
                      <li class="list-group-item"><input type="checkbox" name="is_italian" {{ query_string_list[12] }}> Italian</li>
                      <li class="list-group-item"><input type="checkbox" name="is_mediterranean" {{ query_string_list[13] }}> Mediterranean</li>
                      <li class="list-group-item"><input type="checkbox" name="is_mexican" {{ query_string_list[14] }}> Mexican</li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>

            <!-- Submit Button -->
            <hr style="color: white; margin-top: 0px;">
            <button type="submit" class="btn btn-signup fw-medium">Apply Filters</button>
          </div>
        </div>
      </form>
    </div>

    <!-- Right Column (Recipe Cards) -->
    <div class="col-lg-9 col-md-8">
      {% if recipes %}
        <div class="row">
          {% for recipe in recipes %}
            <!-- Recipe Card -->
            <div class="col-lg-3 col-md-6 col-sm-12 py-2">
              <div class="card w-100 h-100" style="box-shadow: -3px 3px 8px 0 rgba(100, 100, 100, 0.2);">
                <img class="card-img-top" src="{{ recipe.image_url }}" alt="No Image">
                
                <div class="card-body d-flex flex-column">
                  <h5 class="card-title" style="margin-top: -5px;">{{ recipe.title }}</h5>
                  <hr style="margin-top: 0px; margin-bottom: 10px;">
                  <p class="card-text" style="margin-bottom: 2%;"><strong>Servings:</strong> {{ recipe.serving_size }}</p>
                  <p class="card-text" style="margin-bottom: 2%;"><strong>Prep Time:</strong> {{ recipe.prep_time }}</p>
                  <p class="card-text" style="margin-bottom: 0%;"><strong>Cook Time:</strong> {{ recipe.cook_time }}</p>
                  <a class="stretched-link" href="{{ url_for('views.RecipeView', recipe_id=recipe.id) }}"></a>
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
      {% endif %}
      {% if not recipes %}
        <div class="d-flex justify-content-center align-items-center" style="height: 100vh;">
          <h2 align="center">Looks Like No Recipes Were Found.</h2>
        </div>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

website/templates/Home.html
{% extends "base.html" %} {% block title %}Home{% endblock %}
{% block content %}
<h1 align="center" style="margin-top: 1rem;">Welcome To RecipeRepo!</h1>
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-3 col-md-3" style="margin-left: 15px; margin-right: 15px; margin-top: -2.5%;">
      <img src="/static/images/bacon-bbq-cheeseburger.jpg" class="img-thumbnail">
      <img src="/static/images/chicken-tikka-masala.jpg" class="img-thumbnail">
    </div>
        
    <div class="col">
      <h3 align="center">~ About Us ~</h3>
      <p align="left">Welcome to RecipeRepo, your ultimate online recipe organizer and explorer! We're passionate about making cooking easier and more enjoyable by providing a seamless way to save, organize, and discover recipes from around the world.</p>
      <p align="left">Whether you're a seasoned chef or just starting out, our platform allows you to store your favorite recipes, customize collections, and explore new culinary ideas. With intuitive search features, dietary filters, and a user-friendly interface, RecipeRepo is designed to help you find inspiration and keep all your kitchen creations in one convenient place. Let's make cooking simple, fun, and delicious together!</p>
  
      <h3 align="center">Member Login</h3>
      <div class="d-flex justify-content-center" style="margin-bottom: 30px;">
        <a href="{{ url_for('auth.login') }}" class="btn btn-login fw-medium">Log In</a>
      </div>
  
      <h3 align="center">New User</h3>
      <div class="d-flex justify-content-center">
        <a href="{{ url_for('auth.sign_up') }}" class="btn btn-signup fw-medium">Sign Up</a>
      </div>
    </div>

    <div class="col-lg-3 col-md-3" style="margin-left: 15px; margin-right: 15px; margin-top: -2.5%;">
      <img src="/static/images/overnight-cinnamon-rolls.png" class="img-thumbnail">
      <img src="/static/images/italian-beef-sandwiches.png" class="img-thumbnail">
    </div>
  </div>
</div>

<div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvas1" aria-labelledby="accountOffcanvasLabel" aria-hidden="true">
    {% if user.is_authenticated %}
      <form method="POST" class="needs-validation" id="OffcanvasForm" action="/Account" novalidate>
        <div class="offcanvas-header">
          <h5 class="offcanvas-title" id="offcanvasExampleLabel">My Account Info</h5>
          <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
          <hr class="margin-top: 0px; margin-bottom: -10px;">
        </div>
        
        <div class="offcanvas-body">
          <h6>First Name</h6>
          <div class="input-group">
            <span class="input-group-text"><i class="bi bi-person-fill"></i></span>
            <input type="text" class="form-control" name="account_first_name" id="account_first_name" value="{{ user.first_name }}">
            <div class="invalid-feedback">Field Cannot Be Empty</div>
          </div>
          
          <h6 style="margin-top: 15px;">Last Name</h6>
          <div class="input-group" style="margin-top: 10px; margin-bottom: 10px;">
            <span class="input-group-text"><i class="bi bi-person-fill"></i></span>
            <input type="text" class="form-control" name="account_last_name" id="account_last_name" value="{{ user.last_name }}">
            <div class="invalid-feedback">Field Cannot Be Empty</div>
          </div>
          
          <h6 style="margin-top: 15px;">Email Address</h6>
          <div class="input-group">
            <span class="input-group-text"><i class="bi bi-envelope-fill"></i></span>
            <input type="text" class="form-control" name="account_email" id="account_email" value="{{ user.email }}">
            <div class="invalid-feedback">Please Enter A Valid Email Address</div>
          </div>
          
          <hr style="color: white; margin-bottom: 0px;">
          <button type="submit" class="btn btn-signup">Save</button>

        </div>
      </form>
    {% else %}
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasExampleLabel">My Account Info</h5>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        <hr class="margin-top: 0px; margin-bottom: -10px;">
      </div>

      <div class="offcanvas-body">
        <h6 align="center">You're not logged in!</h6>

        <p align="center">Log in here:</p>
        <div align="center" style="margin-top: -10px;">
          <a href="{{ url_for('auth.login') }}" class="btn btn-login fw-medium">Log In</a>
        </div>

        <p align="center" style="margin-top: 15px;">Or sign up:</p>
        <div align="center" style="margin-top: -10px;">
          <a href="{{ url_for('auth.sign_up') }}" class="btn btn-signup fw-medium">Sign Up</a>
        </div>
      </div>
    {% endif %}
  </div>

  <script>
    document.addEventListener('DOMContentLoaded', event => {
      if (sessionStorage.getItem('AccountCanvasTrigger') === 'true') {
        offCanvasObject = document.querySelector('#offcanvas1')
        modalForm = document.querySelector('#OffcanvasForm')
        if (modalForm !== null){
          account_resetModalFields(modalForm, event)
        }
        offCanvasObject.classList.toggle('show')

        sessionStorage.removeItem('AccountCanvasTrigger')
      }
    })

    {
      const makeChangeBtn = document.querySelector('#makeChangeBtn')
      modalForm = document.querySelector('#OffcanvasForm')
  
      makeChangeBtn.addEventListener('click', event => account_resetModalFields(modalForm, event), false)
    }
  
    function account_resetModalFields(form, event){
      form.elements.account_first_name.value = "{{ user.first_name }}"
      form.elements.account_last_name.value = "{{ user.last_name }}"
      form.elements.account_email.value = "{{ user.email }}"
      form.elements.account_first_name.classList.remove('is-valid', 'is-invalid')
      form.elements.account_last_name.classList.remove('is-valid', 'is-invalid')
      form.elements.account_email.classList.remove('is-valid', 'is-invalid')
    }
  
    function account_AccountFormValidation(form, event){                
      account_validateFirstName(form, event)
      account_validateLastName(form, event)
      account_validateEmail(form, event)
    }
  
    function account_validateFirstName(form, event){
      var first_name = form.elements.account_first_name.value
      form.elements.account_first_name.classList.remove('is-valid', 'is-invalid')
      if (first_name === ''){
        if (event.type === 'submit'){
          event.preventDefault()
          event.stopPropagation()
        }
        form.elements.account_first_name.classList.add('is-invalid')
      }else{
        form.elements.account_first_name.classList.add('is-valid')
      }
    }
  
    function account_validateLastName(form, event){
      var last_name = form.elements.account_last_name.value
      form.elements.account_last_name.classList.remove('is-valid', 'is-invalid')
      if (last_name === ''){
        if (event.type === 'submit'){
          event.preventDefault()
          event.stopPropagation()
        }
        form.elements.account_last_name.classList.add('is-invalid')
      }else{
        form.elements.account_last_name.classList.add('is-valid')
      }
    }
  
    function account_validateEmail(form, event){
      const emailRegex = /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/
      var email = form.elements.account_email.value
      form.elements.account_email.classList.remove('is-valid', 'is-invalid')
      if (!emailRegex.test(email)){
        if (event.type === 'submit'){
          event.preventDefault()
          event.stopPropagation()
        }
        form.elements.account_email.classList.add('is-invalid')
      }else{
        form.elements.account_email.classList.add('is-valid')
      }
    }
  
    (() => {
      'use strict'
  
      const form = document.querySelector('#OffcanvasForm')
      form.addEventListener('submit', event => account_AccountFormValidation(form, event), false)
    })()
  
    const form = document.querySelector('#OffcanvasForm')
  
    {
      const firstName = form.elements.account_first_name
      firstName.addEventListener('input', event => account_validateFirstName(form, event), false)
    }
  
    {
      const lastName = form.elements.account_last_name
      lastName.addEventListener('input', event => account_validateLastName(form, event), false)
    }
  
    {
      const email = form.elements.account_email
      email.addEventListener('input', event => account_validateEmail(form, event), false)
    }
  </script>
{% endblock %}